### GET - pobierz wszystkie dane
GET http://localhost:3000/api/filters/metadata/1652779096508 HTTP/1.1

### GET - filtry
GET http://localhost:3000/api/filters HTTP/1.1



### PATCH - updatuj wg id
# ROTATE
# CROP
# FLIP
# FLOP
# GRAYSCALE
# RESIZE
# NEGATE
# FORMAT
# TINT
PATCH  http://localhost:3000/api/filters HTTP/1.1
content-type: application/json

{
  "id": 1652782298791,
  "lastChange": "negate",
  "rotate": 90,
  "width": 125,
  "height": 125,
  "format": "png",
  "left": 20,
  "top": 20,
  "r": 255,
  "g": 255,
  "b": 255
}
