class Tags {
    constructor() {
    }
}
let tags = [
    { id: 0, tag: "#love", popularity: Math.floor(Math.random() * 10000) },
    { id: 1, tag: "#instagood", popularity: Math.floor(Math.random() * 10000) },
    { id: 2, tag: "#fashion", popularity: Math.floor(Math.random() * 10000) },
    { id: 3, tag: "#photooftheday", popularity: Math.floor(Math.random() * 10000) },
    { id: 4, tag: "#beautiful", popularity: Math.floor(Math.random() * 10000) },
    { id: 5, tag: "#art", popularity: Math.floor(Math.random() * 10000) },
    { id: 6, tag: "#photography", popularity: Math.floor(Math.random() * 10000) },
    { id: 7, tag: "#happy", popularity: Math.floor(Math.random() * 10000) },
    { id: 8, tag: "#picoftheday", popularity: Math.floor(Math.random() * 10000) },
    { id: 9, tag: "#cute", popularity: Math.floor(Math.random() * 10000) },
    { id: 10, tag: "#follow", popularity: Math.floor(Math.random() * 10000) },
    { id: 12, tag: "#tbt", popularity: Math.floor(Math.random() * 10000) },
    { id: 13, tag: "#followme", popularity: Math.floor(Math.random() * 10000) },
    { id: 14, tag: "#nature", popularity: Math.floor(Math.random() * 10000) },
    { id: 15, tag: "#like4like", popularity: Math.floor(Math.random() * 10000) },
    { id: 16, tag: "#travel", popularity: Math.floor(Math.random() * 10000) },
    { id: 17, tag: "#instagram", popularity: Math.floor(Math.random() * 10000) },
    { id: 18, tag: "#style", popularity: Math.floor(Math.random() * 10000) },
    { id: 19, tag: "#repost", popularity: Math.floor(Math.random() * 10000) },
    { id: 20, tag: "#summer", popularity: Math.floor(Math.random() * 10000) },
    { id: 21, tag: "#instadaily", popularity: Math.floor(Math.random() * 10000) },
    { id: 22, tag: "#selfie", popularity: Math.floor(Math.random() * 10000) },
    { id: 23, tag: "#me", popularity: Math.floor(Math.random() * 10000) },
    { id: 24, tag: "#friends", popularity: Math.floor(Math.random() * 10000) },
    { id: 25, tag: "#fitness", popularity: Math.floor(Math.random() * 10000) },
    { id: 26, tag: "#girl", popularity: Math.floor(Math.random() * 10000) },
    { id: 27, tag: "#food", popularity: Math.floor(Math.random() * 10000) },
    { id: 28, tag: "#fun", popularity: Math.floor(Math.random() * 10000) },
    { id: 29, tag: "#beauty", popularity: Math.floor(Math.random() * 10000) },
    { id: 30, tag: "#instalike", popularity: Math.floor(Math.random() * 10000) },
    { id: 31, tag: "#smile", popularity: Math.floor(Math.random() * 10000) },
    { id: 32, tag: "#family", popularity: Math.floor(Math.random() * 10000) },
    { id: 33, tag: "#photo", popularity: Math.floor(Math.random() * 10000) },
    { id: 34, tag: "#life", popularity: Math.floor(Math.random() * 10000) },
    { id: 35, tag: "#likeforlike", popularity: Math.floor(Math.random() * 10000) },
    { id: 36, tag: "#music", popularity: Math.floor(Math.random() * 10000) },
    { id: 37, tag: "#follow4follow", popularity: Math.floor(Math.random() * 10000) },
    { id: 38, tag: "#makeup", popularity: Math.floor(Math.random() * 10000) },
    { id: 39, tag: "#amazing", popularity: Math.floor(Math.random() * 10000) },
    { id: 40, tag: "#igers", popularity: Math.floor(Math.random() * 10000) },
    { id: 41, tag: "#nofilter", popularity: Math.floor(Math.random() * 10000) },
    { id: 42, tag: "#dog", popularity: Math.floor(Math.random() * 10000) },
    { id: 43, tag: "#model", popularity: Math.floor(Math.random() * 10000) },
    { id: 44, tag: "#sunset", popularity: Math.floor(Math.random() * 10000) },
    { id: 45, tag: "#beach", popularity: Math.floor(Math.random() * 10000) },
    { id: 46, tag: "#instamood", popularity: Math.floor(Math.random() * 10000) },
    { id: 47, tag: "#motivation", popularity: Math.floor(Math.random() * 10000) },
]

module.exports = { Tags, tags }